version: "3.9"
services:
  api-gplan:
    build:
        context: ./docker
        dockerfile: Dockerfile
    container_name: api-gplan
    volumes:
      - ./:/var/www/html
    environment:
      - TZ=America/Sao_Paulo
    # env_file:
    #   - ./api/.env.local
    depends_on:
      gplan-mysql:
        condition: service_healthy
    ports:
      - "8080:80"
  gplan-mysql:
    image: "mysql/mysql-server:8.0"
    container_name: gplan-mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
        MYSQL_ROOT_HOST: "%"
        MYSQL_DATABASE: "${DB_DATABASE}"
        MYSQL_USER: "${DB_USERNAME}"
        MYSQL_PASSWORD: "${DB_PASSWORD}"
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
volumes:
  sql-data-gplan:
networks:
  default:
    name: gplan
